
import React from 'react';

const TermsOfService: React.FC = () => {
  return (
    <section className="pt-32 pb-24 bg-white min-h-screen">
      <div className="max-w-4xl mx-auto px-6">
        <h1 className="text-4xl font-bold text-slate-900 mb-8">Terms of Service</h1>
        <p className="text-slate-500 mb-8">Last Updated: January 2026</p>
        
        <div className="prose prose-slate max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">1. Agreement to Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              By accessing or using GoGoTrip, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, then you may not access the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">2. Description of Service</h2>
            <p className="text-slate-600 leading-relaxed">
              GoGoTrip provides an AI-powered travel planning platform. We use advanced language models to generate travel recommendations and itineraries based on user input.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">3. User Conduct</h2>
            <p className="text-slate-600 leading-relaxed">
              You agree not to use the service for any purpose that is prohibited by these Terms. You are responsible for all of your activity in connection with the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">4. Intellectual Property</h2>
            <p className="text-slate-600 leading-relaxed">
              The service and its original content, features, and functionality are and will remain the exclusive property of TeoCodes and its licensors.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">5. Limitation of Liability</h2>
            <p className="text-slate-600 leading-relaxed">
              In no event shall GoGoTrip, nor its directors, employees, or partners, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">6. AI Disclaimer</h2>
            <p className="text-slate-600 leading-relaxed">
              Travel recommendations are generated by AI and should be verified by the user. GoGoTrip does not guarantee the accuracy of AI-generated content, including business hours, availability, or pricing of recommended locations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">7. Termination</h2>
            <p className="text-slate-600 leading-relaxed">
              We may terminate or suspend access to our service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">8. Changes to Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. What constitutes a material change will be determined at our sole discretion.
            </p>
          </section>
        </div>
      </div>
    </section>
  );
};

export default TermsOfService;
